name: bottom_sheet
version: 2.0.0
description: Flexible bottom sheet with the ability to scroll content even without a list.
repository: "https://github.com/surfstudio/flutter-bottom-sheet"
issue_tracker: "https://github.com/surfstudio/flutter-bottom-sheet/issues"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  surf_lint_rules: ^1.0.0

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ^2.10.0

flutter:
  uses-material-design: true
